ocpmodels/datasets/tests/test_transforms.py, ocpmodels/datasets/transforms.py
This PR implements new features along the transform pipeline, with three of the four inspired by the PhAST transforms out of the [Rolnick group](https://github.com/RolnickLab/ocp/tree/main/ocpmodels/preprocessing).
Documentation is also included for how to use these transforms, but likely a follow up example script would be good.
=> Graph node transforms

ocpmodels/models/dgl/egnn/egnn.py, ocpmodels/models/dgl/egnn/egnn_model/nets.py
This partially addresses #4, where the EGNN embedding layer is now replaced with an `Embedding` table as opposed to straight MLP.
=> EGNN embedding table

ocpmodels/models/dgl/__init__.py, ocpmodels/models/dgl/megnet/__init__.py, ocpmodels/models/dgl/megnet/helper.py, ocpmodels/models/dgl/megnet/layers.py, ocpmodels/models/dgl/megnet/megnet.py
This partially addresses #4. Here we're porting the MEGNet model (attributing to the [Materials Virtual Lab repo](https://github.com/materialsvirtuallab/m3gnet-dgl) with modifications from us) , followed by additional documentation and refactors before implementing the `Embedding` layer change.
Note that this uses a lookup table nodes only: if one wants to play around with make-believe bond orders for edge embeddings, there will be an additional refactor needed.
=> MEGNet embedding table

ocpmodels/models/dgl/megnet/megnet.py
Input dimensionality of each type of data can now be specified, and under the hood will ultimately get projected into the same dimensionality following MLPs. Addresses #8 .
=> Fix MEGNet dimensionalities

ocpmodels/lightning/data_utils.py
This addresses #11 by adding a single line to the base `GraphDataModule` class that saves all hyperparameters except the dataset class because it's not needed, and probably can't serialize it either.
Verified that transform configs also get included in the hparams.yml created by the default logger.
=> Hyperparameter saving in LightningDataModules

ocpmodels/lightning/callbacks.py
This PR creates two simple callback features that are outside of the PyTorch Lightning native set, but are useful for debugging and performance purposes within `matsciml`.
=> Implemented simple callbacks

ocpmodels/datasets/task_datasets.py, ocpmodels/lightning/callbacks.py, ocpmodels/models/base.py, scripts/generate_leaderboard_logs.py, scripts/utils.py
Adds two files to the `./scripts` folder which help in generating submissions to the evalai leaderboard in the correct format.
Fixes a bug in how `chunk_ids` were calculated.
Adds a case in dataset loading for differently formatted s2ef test data. 
Adds callbacks: leaderboard writer, gradient check, nan check (forward pass), and throughput.
=> Add leaderboard submission scripts

.pre-commit-config.yaml, README.md
This PR adds a `pre-commit` configuration file that can be installed with `pre-commit install`.
The commit workflow includes some specific style checks, such as trailing whitespace and catching debug statements and running `black`, as well as static checking with `flake8` including a stack of plugins like `bandit`.
Note that the whole repo doesn't actually conform with these specs right now: it should be done gradually and in a later PR.
=> Pre-commit workflow

.gitignore, .pre-commit-config.yaml, CONTRIBUTING.md, CONTRIBUTORS.md, README.md, examples/model_demos/m3gnet_dgl.py, matsciml/datasets/carolina_db/dataset.py, matsciml/datasets/materials_project/dataset.py, matsciml/datasets/nomad/dataset.py, matsciml/datasets/oqmd/dataset.py, matsciml/datasets/utils.py, matsciml/models/dgl/__init__.py, matsciml/models/dgl/m3gnet.py, matsciml/models/dgl/tests/test_dgl_model_imports.py, matsciml/models/dgl/tests/test_dgl_models.py, pyproject.toml
This PR adds in the matgl repository, which implements the M3GNet model. The default model from matgl needed modification in its forward pass, which is overwritten in the matsciml model file (`./matsciml/models/dgl/m3gnet.py`). Additional modifications may be needed to output only the graph embedding prior to the final layer - this may be added as a feature to matgl itself to prevent the need to copy over code. Two tests are added to check importing the model, and a simple forward pass which checks for output dimensions and gradients. 
The input graph's are also expected to have a different structure, as well as a few more node and edge features. The processing step of matgl ([here](https://github.com/materialsvirtuallab/matgl/blob/0207660e41f7c05c412331541e8ebb98d8c9c1e9/matgl/graph/data. …
=> Adding M3GNet from matgl 

.pre-commit-config.yaml
This PR adds a working version of `isort` into the `pre-commit` workflow, in addition to patching up the `black` specification to something more recent. Both are verified to work on my laptop environment.
=> Pre-commit fix and adding `isort`

examples/model_demos/egnn_pyg.py, matsciml/datasets/transforms/__init__.py, matsciml/datasets/transforms/representations/graphs.py, matsciml/models/base.py, matsciml/models/pyg/__init__.py, matsciml/models/pyg/egnn.py, pyproject.toml
This PR adds a PyTorch Geometric implementation of E(n)-GNN to `matsciml`, and with in, a small number of refactors/fixes to make the process work.
This implementation differs from the `dgl` version, and is significantly more simple and specialized for `matsciml` usage. I did not check for model consistency, but was able to see some model convergence in the training loss.
The auxiliary fixes that were needed:
- Testing it out on `IS2REDataset`, I had to implement a `GraphToGraphTransform` to facilitate cross-framework conversion. DGL -> PyG was needed for this particular case, and the PyG -> DGL case was also implemented albeit untested.
- Refactored batch parsing system: now the `AbstractEncoder` lineage have a `read_batch_size` function that needs to be defined, which for graph …
=> PyG implementation of E(n)-GNN

CONTRIBUTING.md, matsciml/common/types.py, matsciml/models/base.py, matsciml/models/dgl/egnn/egnn.py, matsciml/models/dgl/gaanet/gaanet.py, matsciml/models/dgl/gcn.py, matsciml/models/dgl/megnet/megnet.py, matsciml/models/dgl/mpnn.py, matsciml/models/dgl/schnet_dgl.py, matsciml/models/pyg/egnn.py
This PR adds a bit of flexibility into task development by having a standardized data structure for what models return.
We introduce the `matsciml.common.types.Embeddings` dataclass, which holds `system_embeddings` and `point_embeddings` optional attributes, which house (as the name suggests) system/graph and point/node level embeddings from a model.
Prior to this, models would only return the system/graph-level embedding, which are then used by the task output heads for projection/prediction. In some cases, tasks will would want to operate on the point/node-level embeddings, and so this refactor facilitates that.
Most common models have been refactored to emit this `Embeddings` structure, and I've checked that they still run in the same way as they did before. In `AbstractTask`, which is …
=> Model output refactor

.gitignore, CONTRIBUTING.md, examples/model_demos/faenet_pyg.py, matsciml/common/types.py, matsciml/common/utils.py, matsciml/datasets/materials_project/dataset.py, matsciml/datasets/transforms/__init__.py, matsciml/datasets/transforms/frame_averaging.py, matsciml/datasets/transforms/props.py, matsciml/models/base.py, matsciml/models/common.py, matsciml/models/dgl/egnn/egnn.py, matsciml/models/dgl/gaanet/gaanet.py, matsciml/models/dgl/gcn.py, matsciml/models/dgl/megnet/megnet.py, matsciml/models/dgl/mpnn.py, matsciml/models/dgl/schnet_dgl.py, matsciml/models/pyg/__init__.py, matsciml/models/pyg/dimenet.py, matsciml/models/pyg/egnn.py, matsciml/models/pyg/faenet/README.md, matsciml/models/pyg/faenet/__init__.py, matsciml/models/pyg/faenet/faenet.py, matsciml/models/pyg/faenet/helper.py, matsciml/models/pyg/faenet/layers.py, matsciml/models/tests/test_tasks.py, pyproject.toml
This PR adds the FAENet architecture, and frame averaging transform, which may be used with other architectures. Additionally, a transform for calculating a material's unit cell from lattice parameters is added, which is needed to generate extra keys to use FAENet. 
Original FAENet implementation: https://github.com/vict0rsch/faenet
=> Adding PyG Version of FAENet

.pre-commit-config.yaml, matsciml/models/common.py, matsciml/models/tests/test_output_heads.py, pyproject.toml
This PR implements support for `e3nn` features in support of #72. The main change is addition of `IrrepOutputBlock` that utilizes `e3nn.o3.Linear` instead of the regular PyTorch `Linear` to preserve symmetry representations. The `OutputHead` class was refactored to support use of either `IrrepOutputBlock` or the regular `OutputBlock`.
A simple example for using this workflow is forthcoming, but in the meantime, the API remains pretty consistent between the two workflows via `output_kwargs` in task specifications:
```python
task = ScalarRegressionTask(
...,
output_kwargs={
"block_type": "IrrepOutputBlock",
"input_dim": "10x0e + 20x1e", 
"hidden_dim": "30x0e + 10x1e", 
"output_dim": "0e",
"activation": ["torch.nn.SiLU", None]
}
)
```
Closes #70.
=> Preserving symmetry representations in outputs

.pre-commit-config.yaml
This PR fixes and updates the `pre-commit` specification:
- `language_version` key for `black` is changed from `python3.9` to `python`, which resolves venv issues when it is not found.
- `black` is bumped to `23.7.0`
- `bandit` is a new part of the workflow, which automates scanning for unsafe code practices
=> Pre-commit update

matsciml/models/common.py
Simple bugfix to correct the `residual` keys in final output block creation. 
Closes #77
=> OutputHead Key Correction

matsciml/datasets/transforms/frame_averaging.py
only import from torch_geometric in datasets.transformation.frame_averaging.py when package_registry check for pyg is satisfied
=> Fix issue https://github.com/IntelLabs/matsciml/issues/91

matsciml/models/dgl/m3gnet.py
Adding in the full forward pass block from [matgl m3gnet](https://github.com/materialsvirtuallab/matgl/blob/main/src/matgl/models/_m3gnet.py) and returning a MatSciML `Embeddings` object. Fixes #92.
=> Returning Embeddings from M3GNet

matsciml/datasets/README.md
In response to #85, I wrote up a brain dump of how to use the `matsciml` API to implement new datasets from start to finish.
I suggest reading it from [this link](https://github.com/laserkelvin/matsciml/blob/85-dataset-documentation/matsciml/datasets/README.md) as opposed to reading it from the diffs/commits :)
Would be nice to receive some feedback and contributions from @melo-gonzo and @bmuaz, but also from @JonathanSchmidt1 to see if anything is missing or requires more elaboration, etc. For the purposes of merging, however, I only need @melo-gonzo to approve.
Closes #85.
=> Documentation on how to implement new datasets

examples/datasets/periodic_properties_pipeline.py, matsciml/datasets/transforms/__init__.py, matsciml/datasets/transforms/pbc.py, matsciml/datasets/transforms/representations/graphs.py, matsciml/datasets/utils.py
This PR includes a general transform that will compute edges and distances based on unit cell images. The main use case designed for this is to pipeline with `PointCloudToGraphTransform` to produce graphs that have been wired for periodic boundary conditions, but is designed to be modular (i.e. point clouds could use this too).
A demonstration of its usage is shown in `examples/datasets/periodic_properties_pipeline.py`.
I didn't include it in this PR, but in some ways it supersedes `UnitCellCalculator`. Needs some work to find out how to fully replace it.
The main modifications in `utils.py` are including two functions that A) create Pymatgen `Structure` objects, and B) use `Structure` to compute neighboring atoms while respecting periodic boundary conditions. The new …
=> Periodic properties transform

matsciml/models/pyg/__init__.py, matsciml/models/pyg/mace/__init__.py, matsciml/models/pyg/mace/data/__init__.py, matsciml/models/pyg/mace/data/atomic_data.py, matsciml/models/pyg/mace/data/neighborhood.py, matsciml/models/pyg/mace/data/utils.py, matsciml/models/pyg/mace/modules/__init__.py, matsciml/models/pyg/mace/modules/blocks.py, matsciml/models/pyg/mace/modules/irreps_tools.py, matsciml/models/pyg/mace/modules/models.py, matsciml/models/pyg/mace/modules/radial.py, matsciml/models/pyg/mace/modules/symmetric_contraction.py, matsciml/models/pyg/mace/modules/utils.py, matsciml/models/pyg/mace/tools/__init__.py, matsciml/models/pyg/mace/tools/cg.py, matsciml/models/pyg/mace/tools/checkpoint.py, matsciml/models/pyg/mace/tools/scatter.py, matsciml/models/pyg/mace/tools/torch_tools.py, matsciml/models/pyg/mace/tools/utils.py
This PR closes #116. 
I have not tested for functionality since I know @melo-gonzo has been having some issues, but I've significantly limited the scope of the work to more or less purely code maintenance. A summary:
- `pre-commit` hooks (lint, `black`, and `pyupgrade`) on all submodules of `matsciml.models.pyg.mace`
- Adding `MACE` and `ScaleShiftMACE` to `matsciml.models.pyg` namespace in a consistent manner
- Removed unused imports and superceded type hints
=> Lint and run formatters on MACE codebase

matsciml/models/pyg/mace/tools/scatter.py
This PR closes #123 by reinstating `Optional` as type hints for MACE, as opposed to the Python 3.10 `|` unions that fail to be JIT compiled.
If and when we move to a PyTorch version  with JIT that supports Python 3.10 unions we can probably revert this change back, but until then this ensures the model will run.
=> Replacing union type hints with `Optional` in MACE

.gitignore, examples/model_demos/m3gnet_dgl.py, matsciml/datasets/carolina_db/dataset.py, matsciml/datasets/materials_project/dataset.py, matsciml/datasets/nomad/dataset.py, matsciml/datasets/oqmd/dataset.py, matsciml/datasets/transforms/__init__.py, matsciml/datasets/transforms/matgl_datasets.py, matsciml/models/dgl/tests/test_m3gnet.py, pyproject.toml
This PR upgrades the matgl package to 1.0.0. This includes many refactors on their end. In matsciml, the `M3G` datasets are removed, and replaced by a transform, `MGLDataTransform`, which adds the required keys to train m3gnet. Also added in a test for m3gnet specifically.
=> Upgrade matgl to 1.0.0

examples/model_demos/m3gnet_dgl.py, matsciml/models/dgl/m3gnet.py
With the update to matgl to include [intermediate outputs](https://github.com/materialsvirtuallab/matgl/pull/212) in m3gnet, the required embeddings for the matsciml Embeddings object are easy to grab, and the full forward pass does not need to be copied over.
=> M3GNet Model Refactor

matsciml/datasets/transforms/base.py, matsciml/datasets/transforms/pbc.py, matsciml/datasets/transforms/representations/graphs.py, matsciml/datasets/utils.py
This PR addresses fixes a number of issues pertaining to the periodic property transform workflow:
- An erroneous `in data` condition was interfering with the PyG graph transform under certain circumstances. It was working correctly for like 99% of cases, but in the case that the `all([...])` failed, it would not trigger the branch condition as intended.
- Some structures in Materials Project were failing to produce neighbors, as the structures were incredibly large and nearest atom neighbors were well beyond the 6 Angstrom cutoff. I've added some quasi-helpful exceptions into the mix, as well as added support for a `adaptive_cutoff` flag for the `PeriodicPropertiesTransform` (that gets passed into the subfunction), which will slightly modify the behavior of the neighborhood detection. …
=> Periodic graph transform fixes

matsciml/datasets/transforms/__init__.py, matsciml/datasets/transforms/frame_averaging.py
Frame averaging transform was removed in [this](https://github.com/IntelLabs/matsciml/commit/34d2677c3c51357f1a35f1574dd36e22758f7142) commit by ruff. There doesn't seem to be a great solution to prevent ruff from removing unused imports, and also for allowing * imports. I added `# noqa: F403` to get around this for now.
=> Adding FA Transform Back In

matsciml/datasets/materials_project/dataset.py
mp-traj and gnome add in some new targets, a few are: force and stress. This small update will let the existing MaterialsProjectDataset be usable across all three datasets (mp, mp-traj, gnome). Note that the `magmom` target is giving problems at the moment and is disregarded for now.
=> Update MaterialsProjectDataset for mp-traj and gnome compatibility

.github/workflows/pre-commit-action.yml
This PR adds a workflow to run `pre-commit` on the repository upon pull request to `main`.
=> Adding `pre-commit` workflow to Github actions

matsciml/models/dgl/m3gnet.py, pyproject.toml
Thanks to @JonathanSchmidt1 for opening the issue!
This PR closes #137, which had an unintended bug where the M3GNet embedding table is not correctly mapped to the correct attribute name expected by `AbstractDGLModel`. Consequently, you end up with unused parameters that are picked up when DDP is used.
Per Jonathan's suggestion, this PR just changes the attribute mapping so that the atom table is correctly referenced and no unused parameters are present.
=> Fix for unused atomic embedding table in M3Gnet

.github/workflows/run_pytest_endtoend.yml, matsciml/tests/test_pipeline.py
This PR adds (for now) a simple EGNN end-to-end PyTest and accompanying Github actions workflow definition.
The premise for this is to have at least one example of an end-to-end run, which hopefully preserves functionality regardless of the changes being submitted are. 
I'm open to adding more tests, but this was the simplest one I could think of and is usually my "go to".
=> Add minimal end-to-end workflow

matsciml/models/dgl/tensornet.py, matsciml/models/dgl/tests/test_tensornet.py
This PR updates the embedding object required by matsciml. Previously, and incompatible node embedding was used causing problems with `GradFreeForceRegression` due to tensor size mismatches. Can @smiret-intel and @laserkelvin look to see if this update makes sense for the node embedding?
=> Tensornet Embedding Output Update

.github/workflows/run_pytest_endtoend.yml, .github/workflows/run_pytest_lightning.yml, examples/devices/xpu_example.py, matsciml/__init__.py, matsciml/lightning/__init__.py, matsciml/lightning/ddp.py, matsciml/lightning/xpu.py
This PR adds PyTorch Lightning classes that enable the usage of Intel GPUs, formerly codenamed Ponte Vecchio, with the `matsciml` pipeline.
An example script is provided, which provides the minimum working configuration on a single device.
=> Enable Intel XPU usage and examples

.github/workflows/run_pytest_datasets.yml, .github/workflows/run_pytest_endtoend.yml, .github/workflows/run_pytest_lightning.yml, .github/workflows/run_pytest_models.yml, .github/workflows/run_pytest_repo.yml
This PR closes #155.
The changes in this PR are:
- Added a `pip install` step to every PyTest workflow, which ensures the most up-to-date code is being used for the `pytest` runs.
- Added an environment printing step so that reviewers can double check that new package versions are being used for validating dependency bumps.
=> CI environment fix and validation

examples/model_demos/mace_wrapper.py, matsciml/common/inspection.py, matsciml/models/pyg/mace/__init__.py, matsciml/models/pyg/mace/original/model.py, matsciml/models/pyg/mace/wrapper/model.py, matsciml/models/pyg/mace/wrapper/tests/test_mace_wrapper.py, pyproject.toml
This PR partially addresses #114 by providing a new `MACEWrapper` implementation that, as the name suggests, wraps the upstream MACE model.
Some of the key changes:
- `e3nn` dependency is relaxed, in order to let MACE dictate which version to install for now.
- `mace-torch` is added as a dependency
- A new module, `matsciml.common.inspection`, which provides utility functions for inspecting model arguments. This is used in the `MACEWrapper` workflow to determine which arguments are missing and/or unmapped and can be used in future model implementations
- It wasn't immediately obvious if there were graph-level outputs, and so I took the liberty of just using (by default) sum pooling on the node outputs. Not 100% sure if this makes sense from a modeling perspective, yet, however. 
- The …
=> Upstream MACE implementation

.pre-commit-config.yaml, pyproject.toml
This PR replaces #171, by updating `ruff` in both the pre-commit workflow as well as the `pyproject.toml` development dependency list.
=> Bumping `ruff` to latest 0.3.5

pyproject.toml
This PR temporarily downgrades `torch_geometric` to 2.4.0, due to a breaking change in the abstraction for `MessagePassing.propagate`.
This issue arose running the PyG implementation of EGNN, triggering exceptions about "too many things to unpack" when running `self.propagate`, which for EGNN, expects to return new node features and coordinates. I haven't been able to look at how and where to rectify this yet.
=> Downgrading `torch_geometric` to 2.4.0

matsciml/lightning/callbacks.py, matsciml/lightning/tests/test_sam.py
This PR closes #181 by refactoring the use of `training_step` in the SAM callback, replacing it with `_compute_losses` and thereby removing the recursive relationship between task and callback.
Also made some minor stylistic changes.
=> SAM force regression task fix

matsciml/lightning/callbacks.py, matsciml/lightning/tests/test_sam.py
This PR adds in the SAM callback to `./matsciml/lightning/tests/test_sam.py`, and adds a fix for #184 where the callback was unable to extract losses from multi task/data pipelines.
=> SAM Multi Task/Data Pipeline Fix

matsciml/lightning/callbacks.py
Two bugs are addressed in this PR:
1. In DDP, the pytorch lightning `trainer` api is different, so the original `trainer.model.optimizers` will not work properly. This pr switches the logic to use the task module to get the optimizer names instead, which is consistent across training pipelines.
2. In multi-data training, each dataset does not necessarily have the same amount of samples. When there is sample imbalance, the `_compute_loss()` function only returns losses for datasets that are still being processed. The `optimizer_names` still contain mappings for datasets with no more samples to process, which was causing problems when gathering losses and computing the "global loss". This pr adds a few checks to `extract_optimizer_specific_loss` to fix these issues.
=> SAM Callback DDP and Multi Data Fixes.

matsciml/lightning/callbacks.py
This PR addresses #188 where some optimizers parameter gradients would be `None` due to the optimizer not being used. This is due to each batch of data not necessarily containing data that will be used for each output head. A check is put in place to see if the current optimizer is used by checking what datasets are present in the current batch. If the optimizer is used then SAM runs as normal, otherwise SAM is skipped.
=> SAM Callback Update - Check If Optimizer Is Utilized

examples/tasks/pretraining/denoising_nodes.py, matsciml/datasets/transforms/__init__.py, matsciml/datasets/transforms/pretraining/__init__.py, matsciml/datasets/transforms/pretraining/noisy_positions.py, matsciml/datasets/transforms/pretraining/tests/test_noisy_positions.py, matsciml/models/base.py, matsciml/models/tests/test_tasks.py
This PR adds a pretraining task to `matsciml` as described in [Zaidi _et al._](https://openreview.net/pdf?id=tYIMtogyee), where an encoder/output head is used to predict the noise injected into the input atom positions.
- An example script is given, under `examples/tasks/pretraining` that demonstrates its usage on EGNN+Alexandria dataset
- Implements a `NoisyPositions` data transform inside a `transforms.pretraining` module, which is intended to house other future pre-training transformations
- Included unit tests that span datasets and representations; seems to be all green across supported datasets, point cloud, graphs
- Implements a `NodeDenoisingTask`, which handles the training.
- Included a single unit test using DGL EGNN and Materials Project
=> Noisy node positions pretraining task

matsciml/models/base.py, matsciml/models/tests/test_tasks.py
This PR refactors `ForceRegressionTask` to regress energies by reducing node contributions, as opposed to system-level embedding regression.
- Energy output head sees node embeddings now, rather than graph embeddings
- Define `readout` functions that depend on whether a graph structure is passed, and what framework is used. The reduction can be configured with the _task_ hyperparameter `embedding_reduction_type` 
- `process_embeddings` will pack the node energy contributions into the output dictionary.
=> Node embedding projections for `ForceRegressionTask`

.github/workflows/run_pytest_datasets.yml, .github/workflows/run_pytest_endtoend.yml, .github/workflows/run_pytest_lightning.yml, .github/workflows/run_pytest_models.yml, .github/workflows/run_pytest_repo.yml, pyproject.toml
This PR adds `pytest-pretty` as a dependency to the actions workflows.
- Add `pytest-pretty` to `pyproject.toml` for `dev` specification
- Add `pytest-pretty` and a print formatting configuration to each PyTest workflow
- Configuring `pytest` to ignore deprecation warnings in `pyproject.toml`, which has been a huge (>300) source of text spam
=> Prettifying PyTest output in Github actions

examples/interfaces/ase_multitask_from_pretrained.py, matsciml/interfaces/ase/base.py, matsciml/interfaces/ase/multitask.py, matsciml/interfaces/ase/tests/test_multi_task.py, matsciml/models/base.py
This PR closes #217 by providing an extended interface for mapping multitask models to `ase` workflows.
The main changes include:
- Introduces the `matsciml.interfaces.ase.multitask.AbstractStrategy` class, whose children allows us to implement ways to aggregate the outputs of multitasks.
- Implements the sole concrete class (for now), `AverageTasks`, which does a mean aggregation across the different dataset heads to compute energies/forces. Essentially, if you had `ForceRegressionTask` trained on multiple datasets, we outputs from all.
- Implements a custom `ase_calculate` method for `MultiTaskModule`, which effectively streamlines inference using multitask modules in scenarios like as an ASE calculator. It's named specifically for `ase`, but in the future we can use it as a dedicated …
=> Multitask ASE interface

matsciml/datasets/alexandria/dataset.py, matsciml/datasets/alexandria/tests/test_alexandria.py, matsciml/datasets/base.py, matsciml/datasets/carolina_db/dataset.py, matsciml/datasets/colabfit/dataset.py, matsciml/datasets/colabfit/tests/test_dataset.py, matsciml/datasets/lips/dataset.py, matsciml/datasets/lips/tests/test_lips_reps.py, matsciml/datasets/materials_project/dataset.py, matsciml/datasets/materials_project/tests/test_mp_reps.py, matsciml/datasets/nomad/dataset.py, matsciml/datasets/ocp_datasets.py, matsciml/datasets/oqmd/dataset.py, matsciml/datasets/symmetry/dataset.py
Would close the issue raised in #132 and #227. Renames the `src_nodes` and `dst_nodes` that are used for point cloud featurization to `pc_src_nodes` and `pc_dst_nodes`.
=> Rename src/dst Nodes For Point Cloud Featurization

matsciml/interfaces/ase/base.py, matsciml/models/base.py
This PR adds a base `predict` method to tasks, which is intended to be used for inference workflows. This method acts as a wrapper for the task `forward` call, but includes the additional step of applying the inverse normalization to the outputs, so that they are rescaled appropriately.
A summary of changes:
1. The `predict` definition in `BaseTaskModule`, which is inherited by all tasks except `MultiTaskModule`
2. Refactored the `MultiTaskModule.ase_calculate` to be `predict`, so that the interface is consistent. The workflow is more or less unchanged from before, but relies on `subtask.predict`.
3. For `ForceRegressionTask`, we override the `predict` logic slightly by rescaling both forces and node energies using the energy normalization factor _if_ dedicated normalizers are not …
=> General predict method for tasks

matsciml/models/base.py
This PR applies two changes:
1. In `ForceRegressionTask.predict`, `denorm` from `energy` was erroneously applied to forces, which was the wrong behavior. This PR fixes this by replacing this with just a rescaling based on the energy standard deviation. 
2. `ForceRegressionTask` now overrides `_make_normalizers`, adding a check for the case when energy normalization is specified and not force. In this scenario, we automatically add the correct force normalizer based on copying the energy standard deviation, which should ensure the correct behavior.
=> Force prediction normalization fix

matsciml/models/base.py, matsciml/models/tests/test_task_loss_scaling.py
This PR adds the ability to optionally add a multiplicative scale factor to the loss value for each task head (`scaled_loss = loss * scale_value`). This parameter is an optional input to the specific task being used which maps specified loss scaling keys to existing task keys. Any task keys that do not have a task_loss_scaling key will default to 1. 
Example:
```python
task = ScalarRegressionTask(
**egnn_config,
task_keys=["efermi", "energy_total", "relative_energy"],
task_loss_scaling={"efermi": 1e-5, "energy_total": 1e4},
)
```
In the above example, the two keys `efermi` and `energy_total` will have a specific scale applied, whicle `relative_energy` will default to a scale factor of 1.
=> Optional Task Loss Scaling

matsciml/models/base.py
This PR forcibly overrides the force normalization standard deviation value with an energy one, if both normalizers are present in the `ForceRegressionTask`.
In #234, the new branch condition (if an energy normalizer is created but not a force one) was intended to be a simple QoL improvement by automatically creating a force normalizer based on the corresponding energy standard deviation value. The catch, however, was that this condition I think will only trigger for previously created tasks, or if `task_keys` are not passed, and was not triggering in LiPS training runs (i.e. "force" normalizer was present, but was a standard normal distribution).
This PR makes it so that we compare values of the force and energy `std`, and if they are not equal, the energy `std` value overwrites the …
=> Override force standard deviation with energy

matsciml/models/pyg/mace/wrapper/model.py
There are usecases in which the `hidden_irreps` may need to be passed in as an `o3.Irreps` module, such as `Irreps("16x0e+16x1o+16x2e")`. This update allows the `hidden_irreps` kwarg to be used in the mace wrapper, and defaults to construct this from `atom_embedding_dim` if not supplied.
=> Allow `hidden_irreps` to be passed through the mace wrapper

matsciml/models/base.py
This PR fixes the unintended behavior of not stepping learning rate schedulers during `ForceRegressionTask` training. Because we use manual optimization, this kind of flew under the radar and I caught it while monitoring the learning rate.
The way this is implemented assumes the learning rate is stepped once per epoch: in some cases a per-batch cadence might be desirable, but can cross that bridge when we get there.
=> Manual step for learning rate schedulers in `ForceRegressionTask`

examples/callbacks/autocorrelation.py, examples/callbacks/helper.py, matsciml/datasets/utils.py, matsciml/lightning/callbacks.py, matsciml/lightning/tests/test_helper.py, matsciml/models/base.py
This PR introduces and adds a bunch of changes pertaining to informing the user of things happening under the hood, particularly during training.
One of the big philosophical changes is also focusing more on enabling logging to be done with `TensorBoardLogger` and `WandbLogger`s by writing functions more tailored to them, rather than before where loggers were treated in the abstract entirely.
- Changed the use of coordinates in periodic boundary utilities to use cartesian coordinates, not fractional coordinates. Also included a warning message that looks at the coordinates as part of diagnostics.
- For model training, task modules now include `log_embeddings` and `log_embeddings_every_n_steps` arguments that are saved to `hparams`, which as the pair suggests, allow you to regularly log …
=> Quality of life and helper callback functions

matsciml/models/pyg/mace/wrapper/model.py
This PR replaces the default MACE atomic energies dictionary with the total free ion energy, instead of just a tensor of ones. Arguably this is more principled, but makes the default configuration a little more opinionated.
=> Default MACE atomic energies

matsciml/models/base.py
The PR removes an extra backprop call that was included in `ForceRegressionTask`.
=> Purge One Unnecessary Backprop Call

matsciml/models/base.py, matsciml/models/dgl/tests/test_m3gnet.py, matsciml/models/dgl/tests/test_tensornet.py, matsciml/models/pyg/mace/wrapper/tests/test_mace_wrapper.py, matsciml/models/pyg/tests/test_egnn.py, matsciml/models/pyg/tests/test_faenet.py
This PR updates some PyTests which constantly fail - this will make interpreting the CI results from PR's much easier.
* SyntheticPointGroupDataset is added to datasets skipped in the forward pass test because it does not make sense to use with the transforms specified. If necessary, we can add a separate test for this dataset which is less generic.
* Bumps the threshold for failure of model output predictions from 1,000 to 10,000 so the test will pass
*  Fixes how MultiTaskLitModule handles the case when task keys are specified in the `MultiTaskLitModule`. Honestly not sure if this bit of code is even necessary if the task keys are specified in the individual tasks which make up the `MultiTaskLitModule`, but the fix is implemented anyway. Note that this test has been consistently skipped …
=> Updating Some Pytests

matsciml/lightning/callbacks.py
This PR fixes an error due to Lightning's API changes to the `on_before_optimizer_step` hook, which no longer requires an optimizer index to be passed.
=> Updating `ManualGradientClip` hook

matsciml/models/base.py, matsciml/models/losses.py, matsciml/models/tests/test_losses.py, matsciml/models/tests/test_task_loss_scaling.py
This PR adds support for MSE and L1 loss functions that are weighted by the number of atoms in each graph in the `matsciml.models.losses` module.
In order to enable usage of these functions with tasks that have both scalar (e.g. energy) and vector (e.g. force) targets, I've had to refactor `loss_func` as an argument to all tasks to support a dictionary mapping, whereby each key corresponds to a `task_key`, and the passed function the loss for that corresponding target. As an example:
```python
ForceRegressionTask(
...,
loss_func={"energy": matsciml.models.losses.AtomWeightedMSE, "force": nn.MSELoss},
...
)
```
This does not break previous specifications: if a loss module is passed by itself (e.g. `loss_func = nn.MSELoss()`), the `task_keys.setter` method copy the function to be used for …
=> Atom weighted loss functions and `loss_func` argument refactor

matsciml/models/base.py
This PR/commit fixes checkpoint saving in the round-trip process.
The problem lies with `ExponentialMovingAverageCallback` creating an `ema_module` attribute that is not normally part of tasks, otherwise leading to a lot of manual wrangling and remapping of `state_dict` when trying to load a checkpoint.
This PR addresses the issue by overriding `on_save_checkpoint` in `BaseTaskModule` and `MultiTaskLitModule`, where if there an `ema_module` exists at the time of checkpoint saving, we overwrite the corresponding `state_dict` tensors using the averaged weights.
This would impact training restarts since the weights are discontinuous, but the main intention of this is to facilitate easy reloading for inference.
=> Fixing checkpoint mechanism for exponential moving average

matsciml/datasets/__init__.py, matsciml/datasets/materials_project/__init__.py, matsciml/datasets/materials_project/dataset.py
This PR adds a subclass of Materials Project as the `MaterialsTrajectoryDataset`, which focuses specifically on energy/force/stress regression tasks.
For the energy, we use the corrected total energy key, allowing the dataset to be used with `ForceRegressionTask` without further modification.
=> Implementing `MaterialsTrajectoryDataset`

examples/callbacks/loss_scheduling.py, matsciml/lightning/callbacks.py, matsciml/lightning/loss_scaling.py, matsciml/lightning/tests/test_loss_scaling_schedules.py
This PR adds a new callback, called `LossScalingScheduler`, and scheduler classes that will modify the relative loss weights over the course of training.
- Two types of schedulers are implemented: `LinearScalingSchedule` and `SigmoidScalingSchedule`. The former will generate a linear ramp from start to end over steps or epochs, and the latter gives a gradual ramp up in the form of a sigmoid curve.
- The `LossScalingScheduler` is configured by passing schedules that are mapped to task keys, and for every training step or epoch (set by the schedules), applies a new value of the weighting to the appropriate task.
- The example script `examples/callbacks/loss_scheduling.py` is provided to show how it is configured.
This is useful for implementing curricula, where we prioritize learning of …
=> Implementing loss scaling scheduler callback and schedulers

matsciml/datasets/transforms/pretraining/noisy_positions.py
This PR adds a flag to rescale the noise targets for noisy nodes prediction, as per Liao 2024. We also modify the default scale value to be much larger.
=> Noisy node modification

experiments/README.md, experiments/task_config/task_config.py
This PR addressed #263 for loading checkpoints using the experiments cli. Local or WandB stored checkpoints may be loaded and used for continual training, or encoder weight transfer to a new task. Checkpoints associated with training from the `MultiTaskLitModule` are processed using `matsciml.models.multitask_from_checkpoint` which has limited functionality at the moment, and is only suited for continuing training.
=> Allow Loading of Checkpoints in Experiments Pipeline

experiments/configs/models/chgnet_dgl.yaml, matsciml/models/dgl/__init__.py, matsciml/models/dgl/chgnet.py, matsciml/models/dgl/m3gnet.py, matsciml/models/dgl/tensornet.py, matsciml/models/dgl/tests/test_chgnet.py, pyproject.toml
This PR takes over dependabot PR #269 and also includes the addition of CHGNet from `matgl` which was introduced in `matgl-v1.1.0`. The PR also includes updates to `TensorNet` forward pass which still must be copied in manually.
=> Matgl upgrade to 1.1.3 + CHGNet Integration

matsciml/interfaces/ase/base.py
Related to #275 
Part of the problem is ase atoms is missing `ptr` and `batch` when converting to dictionary.
=> add missing data in format atoms

matsciml/lightning/callbacks.py
This PR refactors SAM to allow the ability to specify a number of steps or epochs to delay sharpness awareness by adding the `skip_step_count` and `skip_epoch_count` parameters to the `SAM.__init__`. The former accepts integers, which specifies the minimum number of steps to pass before SAM activates, while the latter accepts both integers and a fraction between [0,1].
Additionally, a configurable logger has been added to `SAM`, which informs the user when the gradient norm goes below machine epsilon, i.e. indicating numerical instability. Logging is not on by default.
=> SAM callback step/epoch skipping configuration

docs/source/conf.py
This PR closes #285 by adding a simple one-line configuration to the `sphinx` `conf.py`, which globally makes sure that `autoclass` will also use the docstring for `__init__` when generating documentation.
=> Configuring `sphix` to use class `__init__` docstrings

examples/callbacks/SAM.py, matsciml/lightning/callbacks.py
This PR fixes bugs associated with the `skip_*` configuration options to the SAM callback introduced in #284:
- Fixed the nothing logical comparison for `skip_epoch_count` and `skip_epoch_count` in `__init__`, which meant any value of `skip_epoch_count` would fail the assertion
- Changed `is_integer` checks to `isinstance(skip_epoch_count, float)`; this was a mistake from my IDE that confused me into thinking it was a method for `float` _as well as_ strings.
- Added a logging step that reports which epoch SAM when a fractional value is passed to `skip_epoch_count`
=> SAM configuration check fixes

experiments/utils/utils.py
This PR addresses the issue raised in #290 by passing nested classes and init_args as an *args style argument instead of kwargs.
=> CLI `instantiate_arg_dict` Update

docs/source/inference.rst, matsciml/lightning/data_utils.py, matsciml/models/inference.py, matsciml/models/tests/test_parity_inference.py
This PR implements a `ParityInferenceTask` (with the lack of a better naming for it), which is used to run a datasplit through a model to evaluate predicted vs. actual, beyond just looking at reduced metrics like MSE/MAE. This task should be pretty straightforward to set up and run, and does not need additional logger configuration. After running `trainer.predict`, an `inference_data.json` is produced in the experiment folder (`trainer.log_dir/<name>/inference_data.json`) that can then be reviewed offline.
- Implements a `ParityData` structure which is mostly just a helper class for accumulating data.
- Implements the `ParityInferenceTask`, which in itself just provides the `predict_step` and `on_predict_epoch_end` functions to be called in the PyTorch Lightning `predict` pipeline.
- Unit …
=> Parity inference task

docs/source/index.rst, docs/source/inference.rst, matsciml/lightning/data_utils.py, matsciml/models/inference.py
This PR provides some fixes to the `ParityInferenceTask` implemented in #294.
- Fixes incorrect mapping the in `predictions` property of `ParityData`, which caused targets and predictions to return the same tensor.
- Fixes missing entry in documentation for the general inference page
- Fixed mapping for `collate_fn` in the predict dataloader, in the case that only `pred_split` is specified and `self.dataset` is not defined as a `Dataset` object.
- QoL update to `BaseInferenceTask` class methods, allowing specific tasks to be loaded in, as well as a simplified pipeline to load in an artifact from `wandb`.
=> Fixes to parity inference task

docs/source/best-practices.rst, docs/source/inference.rst, docs/source/training.rst
This PR adds additional documentation pertaining to training, partially addressing #280:
- Task API details, up to date to what tasks available today
- Updated best practices, detailing target normalization and loss scaling
=> Training documentation update

matsciml/interfaces/ase/base.py, matsciml/interfaces/ase/tests/test_ase_calc.py
This pr updates the ASE calculator interface to accommodate a few changes:
* Use models that were not trained with matsciml. This eliminates the requirement for the model to be one of `ForceRegressionTask`, etc. 
* Map from model output keys to keys that are expected by ASE. Currently, the calculator manually renames model outputs to expected outputs by ase, for example the model output `force` gets mapped into `forces`. This mapping should now be passes as a dictionary to the calculator on instantiation if required. 
* The calculator will now iterate through the properties passed into `_calculate` to build the results dictionary.
* Add the `concatenate_keys` function which also adds properties to PyG graphs that are expected by models like MACE, add a few extra keys to `_format_atoms`, …
=> ASE Calculator Updates

docs/source/best-practices.rst, docs/source/datasets.rst, matsciml/datasets/lmdb_cli.py, pyproject.toml
This PR adds a big QoL oriented CLI, which provides some high level functionality for inspecting LMDB datasets.
- Adds a `matsciml.datasets.lmdb_cli` module, which houses a `click`-based interface with multiple commands that perform various LMDB inspection tasks
- Updates `pyproject.toml` to install `lmdb_cli` as a "script", which allows you to access the CLI after installing `matsciml` simply by running `lmdb_cli` in the command line.
- Accompanying documentaton
=> LMDB traversal cli

docs/source/training.rst, matsciml/models/losses.py, matsciml/models/tests/test_losses.py
This PR implements a dynamic quantile-based loss, which computes and rescales specified loss functions depending on quantiles bins within a batch. An accompanying suite of tests will test argument capabilities as well as the end-to-end training with a nominal `EGNN` and `ForceRegressionTask`.
How the loss function works is detailed in the docstring. At a high level, we take the targets and compute their respective quantiles, and use these values to bin the targets as to allow the user to define which ranges to (de)emphasize.
=> Quantile-based loss mechanism

matsciml/datasets/transforms/pbc.py, matsciml/datasets/utils.py
This PR resolves #304 by refactoring `PeriodicPropertiesTransform` in two ways:
1. We will reuse a serialized `structure` if it is interpreted as a `pymatgen.core.Structure` for the periodic boundary neighbors calculation, and return directly.
2. If the above condition fails, we'll continue down the old path, but `Lattice.from_parameters` is now passed `vesta=True` in all cases if creating from lattice parameters. This set up to happen in both the transform, as well as the subroutine `matsciml.datasets.utils.make_pymatgen_periodic_structure`.
The impact of this change is likely only with datasets that do not have a `cell` attribute in their data. e.g. `LiPSDataset` and Open Catalyst expose `cell` which is used for the `Lattice` creation, and if the fully qualified lattice matrix is given …
=> `pymatgen` structure creation patch

README.md, conda.yml, matsciml/common/packages.py, pyproject.toml
This PR is intended to significantly simplify the `matsciml` installation process.
1. We provide the exact `pip` command to install all dependencies, which provide the necessary binary distribution links for both PyG and DGL.
2. Included refreshed `conda.yml` specification, which should now give the equivalent process as `pip` but also wrapping it in a managed environment.
3. We relax the `dgl` requirement, which AFAIK does not have a strict requirement anymore, and by unpinning it makes it less likely to run into issues to missing GraphBolt, etc.
4. Updated `matsciml.common.package` to be a little more specific about the package dependencies that fail most frequently, i.e. DGL and PyG. We will actually try and load in these packages and report back any exceptions, rather than just …
=> Relaxed `pyproject.toml` specifications and improved dependency resolution

matsciml/models/losses.py
This PR fixes the inability to import `BatchQuantileLoss` from the `losses` submodule, even if importing it directly with `from matsciml.models.losses import BatchQuantileLoss`, as it was accidentally omitted from the module's `__all__` definition.
=> Adding `BatchQuantileLoss` to `__all__`

matsciml/datasets/tests/test_transforms.py, matsciml/datasets/transforms/pbc.py, matsciml/datasets/utils.py
This PR adds a flag to the `PeriodicBoundaryCondition` transform to use either `pymatgen` or `ase` as a backend. The ASE backend is implemented and makes use of the [NeighborList](https://wiki.fysik.dtu.dk/ase/_modules/ase/neighborlist.html#NeighborList) utility in ASE. This requires creating an atoms object, and specifying a cutoff distance per node. The two functions `calculate_ase_periodic_shifts` and `calculate_periodic_shifts` are quite similar, however hard to combine due to the dependency on the different backends, so they are kept separate for now. 
Some parameters that may have an impact on results:
`NeighborList`: `self_interaction`, `bothways`
`Atoms`: `pbc`
For example, blindly applying PBC in x, y, and z for a structure which is not meant to be periodic in these directions …
=> ASE Backend For PBC Computation

matsciml/__init__.py, matsciml/common/packages.py, matsciml/lightning/__init__.py, matsciml/lightning/xpu.py, matsciml/models/pyg/__init__.py
This PR uses the package registry a little bit more uniformly in determining which optional dependencies have been installed and are available.
- To support Intel XPUs being available in upstream PyTorch now, IPEX is no longer a required dependency and the accelerator and DDP strategies are imported if `torch.xpu.is_available()` or if IPEX was successfully imported. A warning will be posted if this module is loaded directly and if neither condition is fulfilled.
- On a similar vein, `torch_scatter` and `torch_sparse` being unavailable  or unimportable would mean _every_ PyG model would not work even if they are not required. This PR adds checks to gracefully try and include those models with explicit `torch_scatter` and/or `torch_sparse` dependencies, and warns the user that they will not …
=> Revising optional package imports

matsciml/models/pyg/__init__.py, matsciml/models/pyg/faenet/layers.py, matsciml/models/pyg/scatter.py, matsciml/models/pyg/schnet.py
This PR closes #313 by refactoring the code base to use the `scatter_sum` ported over by MACE. This allows `FAENet` to be used without the hard `torch_scatter` dependency, along with `SchNet`.
=> Scatter add refactor

matsciml/common/tests/test_types.py, matsciml/common/types.py
This PR introduces `pydantic` based data structures for homogenizing model outputs.
1. I've refactored the `Embeddings` class to use `pydantic`, away from the native `dataclass`. There wasn't much modification otherwise, as there aren't as many validation checks to be done with it.
2. The new `ModelOutput` data structure should be the way forward for all models; refactoring that can come later. The main advantage of this class is to homogenize and validate model outputs, and provide meaningful/helpful ways to debug when issues arise (e.g. shape mismatches, batch size with energy predictions, etc.).
At a high level, `pydantic` will run type checking on the inputs (casting when possible), and run user-defined `before` and `after` checks at the `Field` (specific attributes) and `Model` …
=> Structured model output type

docs/source/models.rst, matsciml/models/base.py, matsciml/models/pyg/__init__.py, matsciml/models/pyg/mace/wrapper/model.py, matsciml/models/pyg/mace/wrapper/tests/test_mace_wrapper.py, matsciml/models/tests/test_tasks.py
This PR is semi-related to #104, allowing flexibility for wrappers and full implementations to potentially have a common output format that is also "backwards" compatible. It depends on `ModelOutput` from #315, so please review and merge that before this PR.
- Added a private attribute of the base `AbstractTask` class (which graph models inherit) called `__skip_output_heads__`, which `BaseTaskLitModules` will check this to determine if output heads are needed or not. If we do not use them, we do not initialize the `OutputHeads` to save on parameters/ensure we don't have unused parameters.
- I have refactored the `MACEWrapper` as an example of how to do this, and we should do so for other wrappers as well (e.g. `CHGNet`). I've also updated the `sphinx` documentation to detail how this can …
=> Introducing structured model outputs

docs/source/best-practices.rst, matsciml/datasets/transforms/pbc.py, matsciml/datasets/transforms/tests/test_pbc.py, matsciml/datasets/utils.py
This PR closes #317 by allowing optional keyword arguments to the `PeriodicPropertiesTransform` workflow:
- `max_neighbors` provides a hard cap on the **destination** nodes for any atom. A counter is updated within the per-site loop, and will break out if we exceed the `max_neighbors` value.
- `allow_self_loops`, when set to `False` (which is now the default), will filter out self-loops as the last step, just before we return the updated data dictionary.
I also caught and fixed two bugs in the `ase` implementation:
- Using the right variable check for `adapative_cutoff`
- Missing `cell` reshape before passing it into the `einsum`
=> Specifiable options for periodic neighbors calculations

matsciml/datasets/transforms/pbc.py, matsciml/datasets/transforms/tests/test_pbc.py
This PR fixes the logic for removing self-loops in the `allow_self_loops` flag for `PeriodicPropertiesTransform`.
I've rewritten the mask calculation to make it more readable for humans, as well as added a dedicated unit test that explicitly checks for the presence of self-loops to make sure the logic is implemented correctly.
=> Self loop mask fix

matsciml/datasets/utils.py
This PR is related to #321, and makes the edges being returned exactly equivalent to those counted by `ovito`.
The changes made affect the `Edge` dataclass that was being used with either `pymatgen` and `ase` backends for periodic boundary calculations; the `__eq__` and `__hash__` methods now compare `image` indices without considering phase. The result is that edges are kept in `set`s as __undirected__ and equivalent by mirror symmetry.
=> Edge count fix

matsciml/common/tests/test_types.py, matsciml/common/types.py
This PR fixes the issue where a batch size of 1 will cause the `ModelOutput` model validation to fail for `standardize_total_energy`, where a single scalar wrapped in a `torch.Tensor` returns an `ndim != 1` with an empty `torch.Size([])` for the shape.
The fix makes it so that the check that particular check is skipped if there is a single element in `total_energies` after all of the homogenizing work is done. I've also parameterized the corresponding unit test to include a number of different batch sizes, including one.
=> Model output validation fix

Dockerfile.xpu, docker/Dockerfile.xpu, docker/entrypoint.sh, docs/source/index.rst, docs/source/schema.rst, entrypoint.sh, matsciml/datasets/generic.py, matsciml/datasets/schema.py, matsciml/datasets/tests/test_schema.py, matsciml/datasets/utils.py, pyproject.toml
This PR introduces classes in preparation for a big refactor, emphasizing on reproducibility and generally "explicit is better than implicit". The eventual goal would be to replace currently defined LMDB datasets with the HDF5 + fully specified schema: the former being a better known and less problematic binary data format, and the latter meaning all datasets can share the same Python implementation, but be fully documented *and* validated at runtime.
- Leans on `pydantic` schema definition and validation quite heavily, up to and including array shape validation in `DataSampleSchema`, and fully documented datasets with `DatasetSchema`.
- Schema provides consistent field names, which should phase out `DataDict` and any ambiguity in the pipelines of what key maps to what.
- As seen in …
=> Data schema and HDF5 data support

matsciml/datasets/tests/test_edge_logic.py, matsciml/datasets/transforms/pbc.py, matsciml/datasets/utils.py
This PR modifies the `Edge` class to get exact parity in the number of edges with `ovito`, thanks to code contributed by Sajid Mannan from IIT Delhi.
We introduce an `is_undirected` flag to the `Edge` class that modifies the behavior of the `__eq__` for this class, which propagates to the behavior of how edges are treated in `set()` for determining uniqueness.
I've added a documented set of tests to explain what the expected behavior of the edge sets are.
=> Final edge creation

matsciml/datasets/utils.py
This PR fixes the edge counts in the directed case (i.e. with symmetric edges) being overly aggressively filtered out.
I've refactored where the `set` based filtering of edges is done: instead of in the `Edge` class itself, we simply skip over all of the `set` loops if `is_undirected=False`. In other words, if `is_undirected=False`, we simply return the edges out of `ase` or `pymatgen` neighbor lists.
=> (Pen)ultimate edge logic fix

matsciml/datasets/schema.py
This PR fixes an issue with collating PyG graphs in `BatchSchema`, where we relied on a non-existent method for determining the number of edges.
The fix was to swap the non-existent method with `edge_index.size(-1)`, which is a reliable way to get the number of edges per graph.
=> `BatchSchema` collate fix for PyG graphs

matsciml/models/base.py
This PR attempts to correct broadcasting issues due to shape mismatches in loss calculations.
This was brought on by the realization that broadcasting works a little differently (from some time ago) when tensor shapes are mismatched. In particular, labels come out of the pipeline with an extra dimension (e.g. `[N, 1]`) compared to graph readouts. The resulting behavior is actually very different from the intention:
```python
>>> y
tensor([0.0551, 0.2665, 0.4638, 0.3288, 0.1201, 0.1515, 0.9187, 0.4527])
>>> x
tensor([[0.0961],
[0.6194],
[0.3628],
[0.5289],
[0.2046],
[0.0989],
[0.6621],
[0.8717]])
>>> from torch.nn import MSELoss
>>> MSELoss()(y, x)
/python3.12/site-packages/torch/nn/modules/loss.py:610: UserWarning: Using a target size (torch.Size([8, 1])) that is different to the input …
```
=> Loss broadcasting fix

matsciml/datasets/schema.py, matsciml/datasets/validators.py
This PR refactors the `DataSampleSchema` to use `Annotated` abstraction instead of a `field` and `model` validators, and replacing the shape checking with methods in the new `matsciml.datasets.validators` module.
The intention behind these changes are:
1. Ensure that tensors are used first and foremost, which otherwise introduces barriers to usage in the full pipeline because tensors need to be moved to devices, expected dtypes, etc.
2. The tensor annotations in the model schema are now more semantically meaningful; e.g. `CoordTensor` has more implications to it than `NDArray['*, 3']`. For the user/developer, these effectively "named" tensors in the annotations are likely better to work with.
3. Reusable validator workflows: nominally they can be used with batched data as well.
=> Refactor `DataSampleSchema` to use tensors

matsciml/datasets/generic.py, matsciml/datasets/schema.py, matsciml/datasets/tests/test_schema.py, matsciml/datasets/utils.py, matsciml/datasets/validators.py, matsciml/models/base.py
This PR addresses an issue with the existing `BatchSchema` definition, which is done on-the-fly based on what information was actually packed into the individual data samples. The issue with this is that serialization is not possible, which prevents multiple data loader workers being used, which hinders training.
This is solved by creating a static definition of a `BatchSchema` that subclasses `DataSampleSchema`. The scope of testing is on a new HDF5 dataset with PyG graphs, and is functional for multi-GPU training.
Summary of changes:
- Defined `BatchSchema`, subclassing `DataSampleSchema`
- Added a `to` method for `DataSampleSchema` (which is inherited by `BatchSchema`) for data transfers to accelerators
- Added `transfer_batch_to_device` methods to `LightningModule` definitions, which …
=> Static batch schema
